### ISSUE TITLE
Does not work with JMeter 2.5.1

### ISSUE THREAD

**Issue by llehtinen** [smartrics/JMeterRestSampler#2]
RestSampler stopped working when I upgraded to JMeter 2.5.1.

I tracked this down to an API incompatibility in HTTPSampler2 that was introduced to some extent inadvertently (http://markmail.org/message/ztzijaqlccgxz2wz).

This has been fixed by JMeter folks, see https://issues.apache.org/bugzilla/show_bug.cgi?id=52371

However, there was a call from RestSampler to its superclass' (HTTPSampler2) method setDefaultRequestHeaders, which has been completely removed. This method was empty, however, so all that's needed on RestSampler side is to remove the method call.

**Comment by smartrics** [comment]
Thanks for the heads up - I am not supporting this code any more. Sorry!
Though if you want to fork and fix, I'll be happy to merge your pull request
